CREATE DATABASE Consultorio_Dental
GO
USE Consultorio_Dental
GO

CREATE TABLE DENTISTA(
	ID_DENTISTA INT IDENTITY PRIMARY KEY,
	CEDULA INT,
	NOMBRE VARCHAR(50),
	SEXO CHAR(6) CONSTRAINT C_SEXO_DEN CHECK (SEXO IN ('MALE','FEMALE')),
	NACIMIENTO DATE,
	DIRECCION VARCHAR(50),
	TELEFONO VARCHAR(10),
	EMAIL VARCHAR(30),
	USUARIO VARCHAR(25),
	PSW VARCHAR(10) 
)
GO

CREATE TABLE SECRETARIA(
	ID_SECRETARIA int identity primary key,
	NOMBRE VARCHAR(50),
	SEXO CHAR(6) CONSTRAINT C_SEXO_SEC CHECK (SEXO IN ('MALE','FEMALE')),
	NACIMIENTO DATE,
	DIRECCION VARCHAR(50),
	TELEFONO VARCHAR(10),
	EMAIL VARCHAR(30),
	USUARIO VARCHAR(25),
	PSW VARCHAR(10) 
)
GO

CREATE TABLE DENTISTA_SECRETARIA(
	ID_DENTISTA int foreign key references DENTISTA(ID_DENTISTA),
	ID_SECRETARIA int Foreign key references SECRETARIA(ID_SECRETARIA)
    primary key(ID_DENTISTA,ID_SECRETARIA)

)
go

CREATE TABLE PACIENTE(
	ID_PACIENTE INT IDENTITY PRIMARY KEY,
	ID_DENTISTA INT FOREIGN KEY REFERENCES DENTISTA(ID_DENTISTA),
	NOMBRE VARCHAR(50),
	SEXO CHAR(6) CONSTRAINT C_SEXO CHECK (SEXO IN ('MALE','FEMALE')),
	NACIMIENTO DATE,
	DIRECCION VARCHAR(50),
	TELEFONO VARCHAR(10),
	EMAIL VARCHAR(30)
)
GO

CREATE TABLE CITA(
	ID_CITAS INT IDENTITY PRIMARY KEY,
	ID_SECRETARIA INT FOREIGN KEY REFERENCES SECRETARIA(ID_SECRETARIA),
	ID_PACIENTE INT FOREIGN KEY REFERENCES PACIENTE(ID_PACIENTE),
	FECHA DATETIME,
	DESCRIPCION VARCHAR(70)
)
GO
 
CREATE TABLE PAGO(
	ID_PAGO INT IDENTITY PRIMARY KEY,
	ID_PACIENTE INT FOREIGN KEY REFERENCES PACIENTE(ID_PACIENTE),
	FECHA DATE,
	MONTO MONEY,
	PAGO MONEY,
	SALDO MONEY
)
GO

CREATE TABLE DEUDA(
	ID_DEUDAS INT IDENTITY PRIMARY KEY,
	ID_PAGO INT FOREIGN KEY REFERENCES PAGO(ID_PAGO),
	FECHA DATE,
	ABONO MONEY
)
GO
CREATE TABLE RECETA (
	ID_RECETA INT IDENTITY PRIMARY KEY,
	ID_DENTISTA INT FOREIGN KEY REFERENCES DENTISTA(ID_DENTISTA),
	ARCHIVO VARCHAR(50)
)
GO
CREATE TABLE EXPEDIENTE(
	ID_EXP INT IDENTITY PRIMARY KEY,
	ID_PACIENTE INT FOREIGN KEY REFERENCES PACIENTE(ID_PACIENTE),
	ARCHIVO VARCHAR(50)
)